<?php echo $this->navigation('local_navigation')->menu()->setUlClass('nav nav-pills'); ?>
<h2><?php echo sprintf($this->translate('Add language for module "%s"'), $module)?></h2>
<?php if($error):?>
    <div class="text-error"><?=$this->translate($error)?></div>
<?php endif?>
<?php echo $this->form()->openTag($form)?>

<?php echo $this->formCollection($form)?>

<?php echo $this->form()->closeTag()?>