<?php $this->headStyle()->captureStart() ?>
.phrases textarea{
    width: 90%;
}
<?php $this->headStyle()->captureEnd() ?>

<?php $this->headScript()->captureStart()?>
function deleteTranslation(messageId){
    document.getElementById(messageId).value='';
}
<?php $this->headScript()->captureEnd()?>
<?php echo $this->navigation('local_navigation')->menu()->setUlClass('nav nav-pills'); ?>
<h2>Translate language <?=$language?> of module <?=$module?></h2>
<?php if($error):?>
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php echo $error?>
    </div>
<?php endif?>
<form action="" method="post">
    <table class="table phrases">
        <tr>
            <th>№</th>
            <th width="45%"><?php echo $this->translate('Original string')?></th>
            <th width="40%"><?php echo $this->translate('Translation')?></th>
            <th><?php echo $this->translate('Additional')?></th>
        </tr>
        <?php
        if (count($entries)):
            $j = 0;
            foreach ($entries as $i=>$entry):?>
                <?php if(!$entry->msgid) continue; $j++?>
                <tr <?php if (!$entry->msgstr) echo 'class="info"'?>>
                    <td><?php echo $j?></td>
                    <td><?php echo $this->escapeHtml($entry->msgid)?></td>
                    <td><textarea id="translation-<?php echo $i?>" name="entry[<?php echo $i?>][msgstr]" tabindex="<?php echo $j?>"  class="form-control"><?php echo $this->escapeHtml($entry->msgstr)?></textarea></td>
                    <td>

                        <?php /*if(count($entry->getReferences())):?>
                            <ul>
                                <?php foreach ($entry->getReferences() as $reference):?>
                                    <li><?=$reference?></li>
                                <?php endforeach?>
                            </ul>
                        <?php endif*/?>
                        <div class="comments">
                            <textarea name="entry[<?php echo $i?>][comments]"  class="form-control"><?php echo $this->escapeHtml($entry->comments)?></textarea>
                        </div>

                        <div class="additions form-inline">
                            <input type="hidden" name="entry[<?php echo $i?>][hash]" value="<?php echo $entry->getHash()?>" />
                            <input type="hidden" name="entry[<?php echo $i?>][msgid]" value="<?php echo $this->escapeHtmlAttr($entry->msgid)?>" />
                            <input type="hidden" name="entry[<?php echo $i?>][fuzzy]" value="0" />
                            <label class="checkbox-inline">
                                <input type="checkbox" name="entry[<?php echo $i?>][fuzzy]" value="1"
                                    <?php if($entry->getFuzzy()) echo ' checked="checked" '?>
                                />
                                <?php if($entry->getFuzzy()):?>
                                    <span class="label label-warning">Fuzzy</span>
                                <?php else:?>
                                    Fuzzy
                                <?php endif?>

                            </label>
                            <label class="checkbox inline">
                                <input  
                                    type="button"   
                                    class="btn btn-default  btn-xs" 
                                    onclick="deleteTranslation('translation-<?php echo $i?>')"
                                    name="entry[<?php echo $i?>][delete]" 
                                    value="<?php echo $this->translate('Delete')?>" /> 
                            </label>
                        </div>
                    </td>
                </tr>

            <?php endforeach?>
        <?php else:?>
            <tr>
                <td colspan="4"><?php echo $this->translate('There are no entries for translate. Use "Update" option')?></td>
            </tr>
        <?php endif?>

    </table>
    <input type="submit" class="btn" value="<?php echo $this->translate('Go')?>" />
</form>